site_name: リーダブルコード読書メモ
docs_dir: 'docs'


theme:
  name: "material"  # MkDocs for Materialに表示スタイルを切替.
  language: ja    # メニュー言語を日本語に変更.
  icon:           # サイト名横のアイコン画像を変更.
    logo: material/school
    repo: fontawesome/brands/git-alt
  favicon: images/favicon.png  # ファビコン画像の設定.
  features:
    - tabs   # タブ表示を有効化.


# Navigation
nav:
    - はじめに: index.md
    - 第Ⅰ部：表面上の改善:
        - 第2章 名前に情報を埋め込む: 1/2.md
        - 第3章 誤解されない名前:　1/3.md
        - 第4章 美しさ:　1/4.md
        - 第5章 コメントすべきことを知る: 1/5.md
        - 第6章 コメントは正確で簡潔に: 1/6.md
    - 第Ⅱ部 ループとロジックの単純化:
        - 第7章 制御フローを読みやすくする: 2/7.md
        - 第8章 巨大な式を分割する: 2/8.md
        - 第9章 変数と読みやすさ: 2/9.md
    - 第Ⅲ部 コードの再構成:
        - 第10章 無関係の下位問題を抽出する: 3/10.md
        - 第11章 一度に1つのことを:　3/11.md
        - 第12章 コードに思いを込める:　3/12.md
        - 第13章 短いコードを書く:　3/13.md
    - 第Ⅳ部 選抜テーマ:
        - 第14章 テストと読みやすさ: 4/14.md
        - 第15章 「分/時間カウンタ」を設計・実装する: 4/15.md
        - 付録　合わせて読みたい: 4/huroku.md


markdown_extensions:
    - admonition
    - codehilite:
        linenums: true
        guess_lang: false
        use_pygments: false
        noclasses: true
    - toc:
        permalink: true
    - fontawesome_markdown


extra_css:
    # ユーザー個別で効かせたい設定を記述.
    - css/custom.css
    # fontawesome_markdownで使える設定を別途追加.
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"


# Copyright
copyright: 'Copyright © 2010 - 2020 - Classmethod, Inc.'